theme: jekyll-theme-architect

title: What the Thing?
name: What the Thing?

description: Point camera at things to learn how to say them in a different language. Android app built with React Native

author: Thor Denson

author_email: tjdenson@eckerd.edu